var netmemberdirectoryMarkers = [];
var netmemberdirectoryMarkerPrefix = "netmemberdirectory_index_";
var netmemberdirectoryMap = [];

var netmemberdirectoryAttrs = [];

var netMemberDirectoryRegions = {"UNITED STATES" : {
	"ALABAMA": "#70eed1",
	"ALASKA": "#def1fa",
	"AMERICAN SAMOA": "#d09f68",
	"ARIZONA": "#5ba7ed",
	"ARKANSAS": "#4527e6",
	"CALIFORNIA": "#79b9f5",
	"COLORADO": "#9204fe",
	"CONNECTICUT": "#f746ec",
	"DELAWARE": "#8c3feb",
	"DISTRICT OF COLUMBIA": "#c119ee",
	"FLORIDA": "#f55328",
	"GEORGIA": "#50c9ad",
	"GUAM": "#efdcc3",
	"HAWAII": "#4ec15c",
	"IDAHO": "#deebba",
	"ILLINOIS": "#20a498",
	"INDIANA": "#1bccdb",
	"IOWA": "#c2a39e",
	"KANSAS": "#3bafc6",
	"KENTUCKY": "#b4bed7",
	"LOUISIANA": "#ae0fc5",
	"MAINE": "#162bdd",
	"MARSHALL ISLANDS": "#785dc5",
	"MARYLAND": "#2c0f22",
	"MASSACHUSETTS": "#298fa9",
	"MICHIGAN": "#191b9",
	"MINNESOTA": "#5dbd9c",
	"MISSISSIPPI": "#f5a4b2",
	"MISSOURI": "#7e41a2",
	"MONTANA": "#498274",
	"NEBRASKA": "#4498a7",
	"NEVADA": "#1d8944",
	"NEW HAMPSHIRE": "#39bda4",
	"NEW JERSEY": "#8556cc",
	"NEW MEXICO": "#ded636",
	"NEW YORK": "#68a2ee",
	"NORTH CAROLINA": "#7eea5a",
	"NORTH DAKOTA": "#a15576",
	"NORTHERN MARIANA ISLANDS": "#b37091",
	"OHIO": "#e68245",
	"OKLAHOMA": "#c939d3",
	"OREGON": "#4be856",
	"PALAU": "#450c6e",
	"PENNSYLVANIA": "#80af9",
	"PUERTO RICO": "#434bb4",
	"RHODE ISLAND": "#6e70ea",
	"SOUTH CAROLINA": "#26a3bb",
	"SOUTH DAKOTA": "#4a6c85",
	"TENNESSEE": "#8d09f6",
	"TEXAS": "#245717",
	"UTAH": "#8e2f9d",
	"VERMONT": "#fc3115",
	"VIRGIN ISLANDS": "#ea2b37",
	"VIRGINIA": "#a5db80",
	"WASHINGTON": "#6686d3",
	"WEST VIRGINIA": "#df3591",
	"WISCONSIN": "#82fae2",
	"WYOMING": "#e0d46c"
},
};


function load(attrs){
	var mapId = "netmemberdirectory_map" + attrs["count"];
	netmemberdirectoryMap[attrs["count"]] = new google.maps.Map(document.getElementById(mapId), {
		center: new google.maps.LatLng(47.6145, -122.3418),
		zoom: 4,
		//mapTypeId: 'roadmap'
	});
	var infoWindow = new google.maps.InfoWindow;

	var geocoder = new google.maps.Geocoder();
	var location = attrs["center"];//"United States";
	geocoder.geocode( { 'address': location }, function(results, status) {
		if (status == google.maps.GeocoderStatus.OK) {
			netmemberdirectoryMap[attrs["count"]].setCenter(results[0].geometry.location);
		} else {
			alert("Could not find location: " + location);
		}
	});


}

//called by an external function generated by php code
function setAttrs(attrs){
	netmemberdirectoryAttrs.push(attrs);
}

function pinSymbol(color) {
	return {
		path: 'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z',
		//'M 0,0 C -2,-20 -10,-22 -10,-30 A 10,10 0 1,1 10,-30 C 10,-22 2,-20 0,0 z M -2,-30 a 2,2 0 1,1 4,0 2,2 0 1,1 -4,0'
		fillColor: color,
		fillOpacity: 1,
		strokeColor: '#000',
		strokeWeight: 2,
		scale: 1,
	};
}

function getRegionColor(country, state){
	country = country.toUpperCase();
	state = state.toUpperCase();

	if(netMemberDirectoryRegions[country] !== undefined){
		if(netMemberDirectoryRegions[country][state] !== undefined){
			return netMemberDirectoryRegions[country][state];
		}
	}

	return "#ff0000"; //red
}

/**
 * Shows and populates the map. If a record does not have latitude or longitude data it is not displayed.
 * @param attrs
 */
function showMap(attrs){
	//generateRandCol();
	jQuery(document).ready(function(){
		netmemberdirectoryMarkers[attrs["count"]] = [];
//		var customIcons = {
//				Alabama: {
//			        icon: 'http://labs.google.com/ridefinder/images/mm_20_blue.png'
//			      },
//			      California: {
//			        icon: 'http://labs.google.com/ridefinder/images/mm_20_red.png'
//			      }
//			    };

		//alert("Version: " + jQuery.fn.jquery);



		load(attrs); //load the map


		var infoWindow = new google.maps.InfoWindow;
		var sidePanelString = '';
		//add markers
		jQuery.ajax({
			url:  Drupal.settings.basePath + 'netmemberdirectory/ajax',//attrs['ajaxurl'],
			type:'POST',
			//contentType: "application/json",
			dataType:'json',
			data: 'netmemberdirectory_maps_ajax=' + JSON.stringify(attrs),
			success: function(data){
				/*records = data;*/
				records = [];
				jQuery.each(data, function(index, curr){
					records.push(curr);
				});


				if(records == null || records == 'undefined'){
					return;
				}

				records.sort(compareRecord);

				var prevCountry = '';
				var prevState = '';
				jQuery.each(records, function(index, record){


					if(record["latitude"] == null || record["latitude"] == ""
						|| record["longitude"] == null || record["longitude"] == ""){
						return true; //continue i.e. skip the current iteration.
					}
					//netmemberdirectoryListing[record["country"]][[record["state"]] = record; //removed for now - map looks better by itself

					point = new google.maps.LatLng(parseFloat(record["latitude"]),
						parseFloat(record["longitude"]));

					if(typeof record['name'] == 'undefined'){
						record['name'] =='';
					}

					if(typeof record['last_name'] == 'undefined'){
						record['last_name'] = '';
					}

					if(typeof record['employment_org'] == 'undefined'){
						record['employment_org'] = '';
					}
					var html = '<div class="netmemberdirectory_pin_info_window">';
					html += '<p>' + record["name"] + " " + record["last_name"] + " </p>";
					html += '<p>' + record["employment_org"];
					html += '</div>';


					//var icon = customIcons[record["state"]] || {};
					var marker = new google.maps.Marker({
						map: netmemberdirectoryMap[attrs["count"]],
						position: point,
						icon: pinSymbol(getRegionColor(record["country"], record["state"])) //icon.icon
					});


					bindInfoWindow(marker, netmemberdirectoryMap[attrs["count"]], infoWindow, html);
					//sidePanelString += createSidePanelItem(attrs["count"], record, index, prevCountry, prevState);

					prevCountry = record["country"];
					prevState = record["state"];

					netmemberdirectoryMarkers[attrs["count"]][netmemberdirectoryMarkerPrefix + attrs["count"] + "_" + index] = marker;
				});

				//sidePanelString = createListingString();
				jQuery("#netmemberdirectory_map_info_panel" + attrs["count"]).append(sidePanelString);

			}
		})
	});
}

function initMap(){

	jQuery.each(netmemberdirectoryAttrs, function(index,attrs){
		showMap(attrs);
	});
}

function animateMarker(mapIndex, elementID){
	var marker = netmemberdirectoryMarkers[mapIndex][elementID.id];
	netmemberdirectoryMap[mapIndex].panTo(marker.getPosition());

//	if (marker.getAnimation() !== null) {
//	    marker.setAnimation(null);
//	  } else {
	marker.setAnimation(google.maps.Animation.BOUNCE);
//	  }

	(function(mymarker){
		setTimeout(function(){ mymarker.setAnimation(null); }, 1250); // ~ three bounces
	}(marker));
}

function createSidePanelItem(mapIndex, record, index, prevCountry, prevState){
	var toAdd = "<div id=\"" + netmemberdirectoryMarkerPrefix + mapIndex + "_" + index
		+ "\" onclick=\"{animateMarker(" + mapIndex + ","+ netmemberdirectoryMarkerPrefix + mapIndex + "_" + index + ");}\">";

	var lheader = '';
	if(prevCountry != record["country"]){
		lheader += "<span class=\"netmemberdirectory_country_heading\">" + record["country"] + "</span><br>";
	}

	if(prevState != record["state"]){
		lheader += "<span class=\"netmemberdirectory_state_heading\">" + record["state"] + "</span><br>";
	}

	if(record['cst_type'] == 'Individual') {
		var prefix = record["name_prefix"] != "NULL" ? record["name_prefix"] : '';
		var firstname = record["name"] != "NULL" ?
			prefix != '' ? ' ' + record["name"] : record["name"]
			: '';

		var lastname = '';
		if (record["last_name"] != "NULL") {
			if (prefix == '' && firstname == '') {
				lastname = record["last_name"];
			} else {
				lastname = ' ' + record["last_name"];
			}
		}

		var suffix = '';
		if (!(record["name_suffix"] == 'NULL'
			|| (firstname == '' && lastname == '' && prefix == ''))) {
			suffix = ', ' + record["name_suffix"];
		}

		toAdd = lheader + toAdd + "<p class=\"netmemeber_directory_map_listing\">" + prefix + firstname + lastname + suffix + "</p>";
	}else{ ///organization
		toAdd = lheader + toAdd + "<p class=\"netmemeber_directory_map_listing\">" + record["employment_org"] + "</p>";
	}

	toAdd += "</div>";
	return toAdd;
}

function compareRecord(a,b){
	if(a["country"]=='undefined' || a["country"] == "NULL"){
		a["country"] = "Other";
	}

	if(a["state"]=='undefined' || a["state"] == "NULL"){
		a["state"] = "Other";
	}

	if(b["country"]=='undefined' || b["country"] == "NULL"){
		b["country"] = "Other";
	}

	if(b["state"]=='undefined' || b["state"] == "NULL"){
		b["state"] = "Other";
	}

	var c1 = a["country"].toLowerCase();
	var c2 = b["country"].toLowerCase();

	var s1 = a["state"].toLowerCase();
	var s2 = b["state"].toLowerCase();

	if(c1 < c2){
		return -1;
	}

	if(c1 > c2){
		return 1;
	}

	if(s1 < s2){
		return -1;
	}

	if(s1 > s2){
		return 1;
	}
}

function bindInfoWindow(marker, map, infoWindow, html) {
	google.maps.event.addListener(marker, 'click', function() {
		var zoomLvl = map.getZoom();
		var defaultZoom = 8;
		if(zoomLvl < defaultZoom) {
			map.setZoom(defaultZoom);
		}
		map.panTo(marker.getPosition());
	});

	google.maps.event.addListener(marker, 'mouseover', function() {
		infoWindow.setContent(html);
		infoWindow.open(map, marker);
	});
}
